// This file is generated by kconfig_compiler_kf5 from powerplantconfig.kcfg.
// All changes you do to this file will be lost.

#include "powerplantconfig.h"

#include <qglobal.h>
#include <QFile>

class powerplantConfigHelper
{
  public:
    powerplantConfigHelper() : q(nullptr) {}
    ~powerplantConfigHelper() { delete q; q = nullptr; }
    powerplantConfigHelper(const powerplantConfigHelper&) = delete;
    powerplantConfigHelper& operator=(const powerplantConfigHelper&) = delete;
    powerplantConfig *q;
};
Q_GLOBAL_STATIC(powerplantConfigHelper, s_globalpowerplantConfig)
powerplantConfig *powerplantConfig::self()
{
  if (!s_globalpowerplantConfig()->q) {
    new powerplantConfig;
    s_globalpowerplantConfig()->q->read();
  }

  return s_globalpowerplantConfig()->q;
}

powerplantConfig::powerplantConfig( QObject *parent )
  : KConfigSkeleton()
{
  setParent(parent);
  Q_ASSERT(!s_globalpowerplantConfig()->q);
  s_globalpowerplantConfig()->q = this;
  KConfigCompilerSignallingItem::NotifyFunction notifyFunction = static_cast<KConfigCompilerSignallingItem::NotifyFunction>(&powerplantConfig::itemChanged);

  setCurrentGroup( QStringLiteral( "General" ) );

  KConfigCompilerSignallingItem  *itemSomeSetting;
  KConfigSkeleton::ItemBool  *innerItemSomeSetting;
  innerItemSomeSetting = new KConfigSkeleton::ItemBool( currentGroup(), QStringLiteral( "someSetting" ), mSomeSetting, true );
  itemSomeSetting = new KConfigCompilerSignallingItem(innerItemSomeSetting, this, notifyFunction, signalSomeSettingChanged);
  addItem( itemSomeSetting, QStringLiteral( "someSetting" ) );
}

bool powerplantConfig::defaultSomeSettingValue_helper()
{

  return true;
}

powerplantConfig::~powerplantConfig()
{
  if (s_globalpowerplantConfig.exists() && !s_globalpowerplantConfig.isDestroyed()) {
    s_globalpowerplantConfig()->q = nullptr;
  }
}


void powerplantConfig::itemChanged(quint64 signalFlag) {

  switch (signalFlag) {
  case signalSomeSettingChanged:
    Q_EMIT someSettingChanged();
    break;
  }
}

#include "powerplantconfig.moc"

